plugins:
  # - "@salesforce-ux/stylelint-slds" # This is when we use it as npm package.
  - "../stylelint-rules/build"

overrides:
  - files:
      - "**/*.css"
      - "**/*.scss"
    customSyntax: "postcss"
    rules:
      sf-sds/no-slds-class-overrides:
        - true
        - severity: warning
      sf-sds/no-important:
        - true
        - severity: warning
      sf-sds/no-hardcoded-values:
        - true
        - severity: error
      sf-sds/no-hardcoded-values-slds2:
        - true
        - severity: error
      sf-sds/enforce-use-of-utility-classes:
        - true
      sf-sds/no-aura-tokens:
        - true
      sf-sds/lwc-to-slds-token:
        - true
      sf-sds/enforce-bem-usage:
        - true
      sf-sds/no-deprecated-slds-classes:
        - true
      sf-sds/no-deprecated-slds-hooks:
        - true
      sf-sds/no-lwc-custom-properties:
        - true
      sf-sds/no-sds-custom-properties:
        - true
      sf-sds/no-slds-private-var:
        - true
      sf-sds/do-not-use-calc-function:
        - true
      sf-sds/enforce-sds-to-slds-hooks:
        - true
        - severity: error
        
    sourceMap: 
      - false

  - files:
      - "**/*.html"
    customSyntax: "postcss-html"
    rules: {}