root: true
env:
  es2021: true
  node: true
parserOptions:
  ecmaVersion: 2021
  sourceType: module
ignorePatterns:
  - "node_modules/"
overrides:
  - files:
      - "*.html"
      - "*.cmp"
    parser: "@html-eslint/parser"
    plugins:
      - "@salesforce-ux/sds-rules"
    rules:
      "@salesforce-ux/sds-rules/no-bem-class":
        - "error"
      "@salesforce-ux/sds-rules/no-deprecated-slds-classes":
        - "error"

  - files:
      - "*.js"
      - "*.json"
    excludedFiles: "*.js"
    rules:
      "@salesforce-ux/no-bem-class":
        - "error"
      "@salesforce-ux/sds-rules/no-deprecated-slds-classes":
        - "error"